version: "2"

volumes:
   guacamole:
      driver: "flocker"
      driver_opts:
        size: "5GiB"
        profile: "bronze"

services:
  guacd:
    image: glyptodon/guacd
    networks:
      - back
  guacdb:
    build: ./guacdb
    networks:
      - back
    environment:
      - MYSQL_ROOT_PASSWORD=Pass@word1
    volumes:
      - 'guacamole:/var/lib/mysql'
    
  guacamole:
    image: glyptodon/guacamole
    environment:
      - MYSQL_HOSTNAME=guacdb
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=guacamole
      - GUACD_PORT_4822_TCP_ADDR=guacd
      - GUACD_PORT_4822_TCP_PORT=4822
    ports:
      - 8080:8080
    networks:
      - back  
    depends_on:
      - "guacdb"
      - "guacd"
networks:
  back:
    driver: overlay
    driver_opts:
      subnet: "10.0.9.0/24"
