version: '2'

services:
  db:
    image: mariadb 
    volumes:
      - "wordpress:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress_back

  wordpress:
    depends_on:
      - db
    image: wordpress:4.5.2-apache
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress_back
    depends_on:
      - "db"

volumes:
  wordpress:
    driver: "flocker"
    driver_opts:
      size: "1GiB"
      profile: "bronze"

networks:
  wordpress_back:
    driver: overlay
    ipam:
      config:
        - subnet: "172.31.0.0/24"
